default_platform(:ios)

platform :ios do

  desc "TestFlight 빌드 & 업로드"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "/tmp/AuthKey.p8"
    )

    setup_ci if is_ci
    match(type: "appstore", readonly: is_ci, api_key: api_key)

    increment_build_number(
      build_number: ENV["BUILD_NUMBER"] || Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "App/ForP.xcodeproj"
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "App/ForP.xcodeproj",
      code_sign_identity: "Apple Distribution",
      profile_name: "match AppStore com.kihyeonKim.ForP",
      bundle_identifier: "com.kihyeonKim.ForP",
      team_id: "697ACQDW6C"
    )

    build_app(
      workspace: "ForP.xcworkspace",
      scheme: "ForP",
      export_method: "app-store",
      clean: true,
      output_directory: "./build",
      output_name: "ForP.ipa"
    )

    upload_to_testflight(api_key: api_key, skip_waiting_for_build_processing: true)
  end

end
